// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotNetCoreSQLite.Config;

namespace dotNetCoreSQLite.Migrations
{
    [DbContext(typeof(QuoteDbContext))]
    partial class QuoteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11");

            modelBuilder.Entity("dotNetCoreSQLite.Model.Author", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.HasKey("id");

                    b.ToTable("authors");
                });

            modelBuilder.Entity("dotNetCoreSQLite.Model.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT")
                        .HasMaxLength(2000);

                    b.Property<int>("author_id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("authorid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quote_type_id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("quote_typeid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("authorid");

                    b.HasIndex("quote_typeid");

                    b.ToTable("quotes");
                });

            modelBuilder.Entity("dotNetCoreSQLite.Model.QuoteType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("text")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.HasKey("id");

                    b.ToTable("quote_types");
                });

            modelBuilder.Entity("dotNetCoreSQLite.Model.Quote", b =>
                {
                    b.HasOne("dotNetCoreSQLite.Model.Author", "author")
                        .WithMany()
                        .HasForeignKey("authorid");

                    b.HasOne("dotNetCoreSQLite.Model.QuoteType", "quote_type")
                        .WithMany()
                        .HasForeignKey("quote_typeid");
                });
#pragma warning restore 612, 618
        }
    }
}
